version: "3"

services:
  nginx:
    image: nginx
    restart: always
    depends_on:
      - ursa-dev
    ports:
      - "80:80"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d:ro

  ursa-dev:
    image: mtavano/ursadev:0.2.1
    restart: on-failure
    expose:
      - "4069"
