version: "3"

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d:ro

  ursa-dev:
    image: mtavano/ursadev:0.1.2
    restart: on-failure
